Added method to skip to next weekday
mikemartino/standup_notes pull request #3
Opened 2020-03-27 19:52 UTC by jcorrive

* Switched datetimes to dates since we don't care about the time.
* Added method to skip weekends.

2020-03-29 01:47 UTC, mikemartino requested changes

2020-03-29 01:47 UTC, mikemartino commented on standup_notes/__main__.py
> +        return next_weekday(tomorrow)
I love it. And it's a good case for recursion, as you've shown! Yep, fantastic. Thanks dude.

2020-03-29 01:47 UTC, mikemartino commented on standup_notes/__main__.py
> +    week_num = tomorrow.weekday()
This should probably be: 
```suggestion
    day_num = tomorrow.weekday()
```
`week_num` sounds like it's the number of the week in the year (e.g. 1 of 52, 2 of 52, etc.)

2020-03-30 13:01 UTC, jcorrive commented on standup_notes/__main__.py
> +        return next_weekday(tomorrow)
I actually spent a while trying to figure out how to extend a date object but that didn't seem to be working so well for me... Maybe because Python isn't exactly meant to be OO, maybe because I'm dumb. In any case, Stack Overflow said to just create a function like this for a similar use case so here it is :)

2020-03-30 13:04 UTC, mikemartino approved these changes
Yep, that's it. Ship it.

2020-03-30 13:06 UTC, merged